package com.cn.my.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userid;
	private String username;
	private String password;
	private String question;
	private String answer;
	private String createBy;
	private Date createdate;
	private String lastupdataby;
	private Date lastupdatadate;



	public User() {
	}


	public User(String userid, String username, String password,
			String question, String answer, String createBy, Date createdate,
			String lastupdataby, Date lastupdatadate) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.question = question;
		this.answer = answer;
		this.createBy = createBy;
		this.createdate = createdate;
		this.lastupdataby = lastupdataby;
		this.lastupdatadate = lastupdatadate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getLastupdataby() {
		return this.lastupdataby;
	}

	public void setLastupdataby(String lastupdataby) {
		this.lastupdataby = lastupdataby;
	}

	public Date getLastupdatadate() {
		return this.lastupdatadate;
	}

	public void setLastupdatadate(Date lastupdatadate) {
		this.lastupdatadate = lastupdatadate;
	}
}
